name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.13.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "406e38abc82643e30870d13d48d7f3c6316a81d03b7372add6961b34445f1007"

[versions]
forge = "0.2.4-alpha"
minecraft = "1.12.2"
