name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.13.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "975c9c35ec36c3654d7eb49122a2fba8b3debdf0ea050cd030ae8711935e135e"

[versions]
forge = "0.2.4-alpha"
minecraft = "1.12.2"
