name = "Supersymmetry"
author = "SymmetricDevs"
version = "0.1.13.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "664e1b7c034376dde36bb3812a24ccfda3f4af1d8289c68d0f2f3f2f3e6b396a"

[versions]
forge = "0.2.4-alpha"
minecraft = "1.12.2"
